spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 476494788790-ekeggg2l4ro45bht5ntu59rh3is39eua.apps.googleusercontent.com
            client-secret: _hy9ZlTOE9gLzWF4Vp0S-tMm
            scope: profile,email
          naver:
            client-id: IgJywDBLQ6zaaW9cxUBE
            client-secret: C3iCTROO4V
            redirect_uri_template: {baseUrl}/{action}/oauth2/code/{registrationId}
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: naver
          github:
            client-id: 374d6795d522aef0afb1
            client-secret: 13738c0f5242f088cf3f57eab5a0fb70ba3caa54
            scope: read:user
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response




